FROM nkoshell/iss-positioner
MAINTAINER nkoshell <nikita.koshelev@gmail.com>

EXPOSE 80

WORKDIR /opt/iss-positioner/

ONBUILD COPY requirements.txt ./
ONBUILD RUN pip install --no-cache -r requirements.txt

ONBUILD ADD . ./

ONBUILD CMD python -m app
