version: "2"

services:
  periodic:
    image: nkoshell/iss-positioner
    volumes:
      - ./iss-positioner.yml:/opt/iss-positioner/iss-positioner.yml:ro
    links:
      - redis
  redis:
    image: redis:alpine
